blank_issues_enabled: true
contact_links:
  - name: Submit Feedback In-App
    url: https://estradabot.biz/update-log
    about: You can also submit feedback directly from the EstradaBot Update Log page.
